# Generated by Django 5.2.8 on 2025-12-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID da Sessão"
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Visitante",
                    ),
                ),
                (
                    "visitor_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email do Visitante",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciada em"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última Mensagem"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "total_messages",
                    models.IntegerField(default=0, verbose_name="Total de Mensagens"),
                ),
                (
                    "detected_intent",
                    models.CharField(
                        choices=[
                            ("general", "Geral"),
                            ("project", "Projeto"),
                            ("contact", "Contato"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Intenção Detectada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa do Chat",
                "verbose_name_plural": "Conversas do Chat",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Assunto")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False, verbose_name="Lido")),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("password", models.CharField(max_length=100, verbose_name="Senha")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usuário Administrativo",
                "verbose_name_plural": "Usuários Administrativos",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Usuário"), ("assistant", "Assistente")],
                        max_length=10,
                        verbose_name="Papel",
                    ),
                ),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="portfoly.chatconversation",
                        verbose_name="Conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem do Chat",
                "verbose_name_plural": "Mensagens do Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectInquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Nome do Cliente"),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="Email do Cliente"),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone do Cliente",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Mobile", "Mobile"),
                            ("Web", "Web"),
                            ("Desktop", "Desktop"),
                            ("Android", "Android"),
                            ("iOS", "iOS"),
                            ("Game", "Game"),
                            ("IA", "IA"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Projeto",
                    ),
                ),
                (
                    "project_description",
                    models.TextField(verbose_name="Descrição do Projeto"),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Faixa de Orçamento",
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Prazo Desejado",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("reviewing", "Em Análise"),
                            ("contacted", "Contatado"),
                            ("converted", "Convertido"),
                            ("declined", "Recusado"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas do Admin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_inquiries",
                        to="portfoly.chatconversation",
                        verbose_name="Conversa Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Projeto",
                "verbose_name_plural": "Solicitações de Projeto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Basic", "Basic"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Expert", "Expert"),
                            ("Master", "Master"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Nível",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfoly.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidade",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "technologies",
                    models.CharField(max_length=100, verbose_name="Tecnologias"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mobile", "Mobile"),
                            ("Web", "Web"),
                            ("Desktop", "Desktop"),
                            ("Android", "Android"),
                            ("iOS", "iOS"),
                            ("Game", "Game"),
                            ("IA", "IA"),
                        ],
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "link_demo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Link Demonstração",
                    ),
                ),
                (
                    "link_github",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Link GitHub",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="img/projects/%Y/%m/%d",
                        verbose_name="Imagem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfoly.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                ("used", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="portfoly.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperação de Senha",
                "verbose_name_plural": "Tokens de Recuperação de Senha",
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Posição")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Empresa"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "range_time",
                    models.CharField(
                        blank=True, max_length=26, null=True, verbose_name="Tempo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfoly.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiência",
                "verbose_name_plural": "Experiências",
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "remember_me",
                    models.BooleanField(default=False, verbose_name="Lembrar-me"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="portfoly.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Autenticação",
                "verbose_name_plural": "Tokens de Autenticação",
            },
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("linkedin", models.CharField(max_length=100, verbose_name="LinkedIn")),
                ("github", models.CharField(max_length=100, verbose_name="GitHub")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfoly.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes do Usuário",
                "verbose_name_plural": "Detalhes dos Usuários",
            },
        ),
    ]
